# Exported from Render on 2024-10-08T00:01:10Z
services:
- type: web
  name: primerProyectoRender
  runtime: ruby
  repo: https://github.com/marceloesparza/primerProyectoRender
  plan: free
  envVars:
  - key: DATABASE_URL
    sync: false
  - key: RAILS_MASTER_KEY
    sync: false
  - key: WEB_CONCURRENCY
    sync: false
  region: oregon
  buildCommand: ./bin/render-build.sh
  startCommand: bundle exec rails server
version: "1"
